version: "3.6"

services:
  auth-postgres:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=my_database
    volumes:
      - "/Users/nikitakrainev/Desktop/SystemAnalysys/PsSQL-data/:/var/lib/postgresql/data"
    ports:
      - "15532:5432"